// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *News Post → sections*
 */
export interface NewsPostDocumentDataSectionsItem {
  /**
   * title field in *News Post → sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_post.sections[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * descriptions field in *News Post → sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_post.sections[].descriptions
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descriptions: prismic.RichTextField;
}

type NewsPostDocumentDataSlicesSlice = never;

/**
 * Content for News Post documents
 */
interface NewsPostDocumentData {
  /**
   * title field in *News Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: news_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * date field in *News Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: news_post.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Image field in *News Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_post.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * sections field in *News Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: news_post.sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sections: prismic.GroupField<Simplify<NewsPostDocumentDataSectionsItem>>;

  /**
   * Slice Zone field in *News Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewsPostDocumentDataSlicesSlice> /**
   * Meta Title field in *News Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: news_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *News Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *News Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * News Post document from Prismic
 *
 * - **API ID**: `news_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NewsPostDocumentData>,
    "news_post",
    Lang
  >;

export type AllDocumentTypes = NewsPostDocument;

/**
 * Primary content in *Sections → Default → Primary*
 */
export interface SectionsSliceDefaultPrimary {
  /**
   * title field in *Sections → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sections.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Sections → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sections.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Sections Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Sections*
 */
type SectionsSliceVariation = SectionsSliceDefault;

/**
 * Sections Shared Slice
 *
 * - **API ID**: `sections`
 * - **Description**: Sections
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionsSlice = prismic.SharedSlice<
  "sections",
  SectionsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NewsPostDocument,
      NewsPostDocumentData,
      NewsPostDocumentDataSectionsItem,
      NewsPostDocumentDataSlicesSlice,
      AllDocumentTypes,
      SectionsSlice,
      SectionsSliceDefaultPrimary,
      SectionsSliceVariation,
      SectionsSliceDefault,
    };
  }
}
