// Code generated by Slice Machine. DO NOT EDIT.

import { SectionsSlice } from "@/../prismicio-types";
import Sections from "./Sections";

export const components = {
  sections: Sections,
};

export type SliceComponentProps<Slice> = {
  slice: Slice;
  index: number;
  slices: Slice[];
  context: any;
};

export type SectionsProps = SliceComponentProps<SectionsSlice>;
